services:
  - type: web
    name: stock-dashboard
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
